version: "3.8"

services:
  chroma:
      image: chromadb/chroma:latest

      volumes:
        - ./chroma_data:/chroma/.chroma/index
      
      networks:
        - search_net

  retrieval_app:
    image: stanislavlia/retrieval_app:langchain

    ports:
      - 8012:8012

    depends_on:
      - chroma
      - localstack
    
    networks:
      - search_net

  web_ui:
    image: stanislavlia/retrieval_ui:latest

    ports:
      - 8051:8051
    
    depends_on:
      - retrieval_app
      - chroma
      - localstack
    networks:
      - search_net
  
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - PERSISTENCE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    

networks:
    search_net:
      driver: bridge