name: Build and Push Docker Image

env:
  IMAGE_TAG: latest

on:
  push:
    branches: ['main']
    paths:
      - 'retrieval_app_langchain/**'
      - 'web_ui/**'
      - '.github/workflows/**'

jobs:
  push_to_registry:
    name: Push image to Dockerhub
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.OPENAI_API_KEY }}" > ./retrieval_app_langchain/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push retrieval_app image
        run: |
          docker build --no-cache -t stanislavlia/retrieval_app_langchain:${{ env.IMAGE_TAG }} -f ./retrieval_app_langchain/Dockerfile ./retrieval_app_langchain
          docker push stanislavlia/retrieval_app:${{ env.IMAGE_TAG }}
        
      - name: Build and push web_ui image
        run: |
          docker build --no-cache -t stanislavlia/retrieval_ui:${{ env.IMAGE_TAG }} -f ./web_ui/Dockerfile ./web_ui
          docker push stanislavlia/retrieval_ui:${{ env.IMAGE_TAG }}
